ORUComSys/ORUComSys/Models/FormalPostViewModels.cs
using Datalayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ORUComSys.Models {
    public class FormalPostViewModel {
        public int Id { get; set; }
        public ApplicationUser FromUser { get; set; }
        public string PostText { get; set; }
        public HttpPostedFileBase AttachedFile { get; set; }
        public DateTime TimePosted { get; set; }
    }
}

ORUComSys/ORUComSys/Controllers/FormalPostController.cs
using Datalayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Datalayer.Repositories;
using System.IO;
using ORUComSys.Models;

namespace ORUComSys.Controllers {
    [Authorize]
    public class FormalPostController : Controller {
        public FormalPostRepository formalPostRepo { get; set; }

        public FormalPostController() {
            ApplicationDbContext context = new ApplicationDbContext();
            formalPostRepo = new FormalPostRepository(context);
        }

        // GET: FormalPost
        public ActionResult Index() {
            FormalPostViewModel viewModel = new FormalPostViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(FormalPostViewModel postModel) {
            
            // check modelstate.
            if (ModelState.IsValid) {
                // get current user id (the poster's id).
                string currentUser = User.Identity.GetUserId();

                // declare a byte array, set it to the length of the possibly attached file from the view model.
                byte[] attachmentData = new byte[postModel.AttachedFile.InputStream.Length];
                // transfer the byte data to the view model's attached file field.
                postModel.AttachedFile.InputStream.Read(attachmentData, 0, attachmentData.Length);

                // convert to FormalPostModel.
                FormalPostModel modelToSave = new FormalPostModel { PostFromUserId = currentUser, PostText = postModel.PostText, TimePosted = DateTime.Now, AttachedFiles = attachmentData };

                // add to db and save changes.
                formalPostRepo.Add(modelToSave);
                formalPostRepo.Save();

                return RedirectToAction("Index", "Home");
            } else {
                return View();
            }

        }
    }
}

ORUComSys/ORUComSys/Views/FormalPost/Index.cshtml
@model ORUComSys.Models.FormalPostViewModel

@{
    ViewBag.Title = "Create a formal post";
}

<h2>Formal Forum Post</h2>


@using (Html.BeginForm("Index", "FormalPost", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.PostText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostText, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.AttachedFile, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input type="file" name="AttachedFile" accept=".png,.jpg,.jpeg,.pdf,.pptx,.txt,.odt,.docx" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}